variable vpc_id {}
variable network_cidr {}
variable private_subnet_ids {}
variable db_engine_version {}
variable db_storage {}
variable db_instance_class {}
variable dbname {}
variable dbuser {}
variable db_identifier {}
variable skip_db_snapshot {}
variable dbpassword {}
variable db_subnet_group {}
